### ISSUE TITLE
Error: BrowserModule has already been loaded

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [miraxes/ngx-custom-tour#1]
In NgxCustomTourModule you are exporting CommonModule and BrowserAnimationsModule which ends up generating the image attached error. Would it be possible for you not to export CommonModule and BrowserAnimationsModule in your NgxCustomTourModule?

![Screen Shot 2021-12-09 at 15 13 55](https://user-images.githubusercontent.com/4552539/145452706-ef713549-2429-4b6e-854d-9b3af303b9b5.png)

**Comment by miraxes** [comment]
@Luiz-Otavio-Dorigon Thanks for using this library, issue should be resolved in 0.1.4, which is published few seconds ago.

**Comment by Luiz-Otavio-Dorigon** [comment]
This error persists when using in a lazy loading module

**Comment by miraxes** [comment]
Removed  `BrowserAnimationsModule` from imports in 0.1.6 versions, if this doesn't help - I'll fix it tomorrow.
