### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [miraxes/ngx-custom-tour#2]
See the image, when downloading the api the files were not generated correctly. Missing public-api.d.ts, bundles, esm2015, fesm2015, etc...

![Screen Shot 2021-12-09 at 16 34 22](https://user-images.githubusercontent.com/4552539/145463722-eb55b282-b9e9-40c5-8b4f-d183f1ba2bc2.png)

**Comment by miraxes** [comment]
@Luiz-Otavio-Dorigon My bad, was in rush. 0.1.5 published
