### ISSUE TITLE
support for angular 13 and above

### ISSUE THREAD

**Issue by MohammadWasi** [miraxes/ngx-custom-tour#3]

**Comment by MohammadWasi** [comment]
![Screenshot 2022-08-18 at 11 22 46 AM](https://user-images.githubusercontent.com/10944032/185304299-7da28e20-e1da-4b4a-8490-66a0f2f8f5cc.png)

i am getting peer dependency error for angular 13, please provide support for angular 13 and above

**Comment by miraxes** [comment]
Hello, @MohammadWasi 
Can you double check latest version, please?

**Comment by MohammadWasi** [comment]
> Hello, @MohammadWasi Can you double check latest version, please?

Thanks,
