### ISSUE TITLE
0.1.7 SassError: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by noskap** [miraxes/ngx-custom-tour#4]
I just started getting this error in my Angular deployment:
`

SassError: Can't find stylesheet to import.
--
342 | ╷
343 | 14 │ @import "~ngx-custom-tour/styles/styles.scss";
344 | │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
345 | ╵
346 | src/assets/scss/app.scss 14:9  root stylesheet
347 |  
348 | ./src/assets/scss/app.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
349 | HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
350 | SassError: Can't find stylesheet to import.
351 | ╷
352 | 14 │ @import "~ngx-custom-tour/styles/styles.scss";
353 | │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
354 | ╵
355 | src/assets/scss/app.scss 14:9  root stylesheet
356 | at tryRunOrWebpackError (/codebuild/output/src008293549/src/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/HookWebpackError.js:88:9)
357 | at __webpack_require_module__ (/codebuild/output/src008293549/src/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:5049:12)
358 | at __webpack_require__ (/codebuild/output/src008293549/src/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:5006:18)
359 | at /codebuild/output/src008293549/src/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:5077:20
360 | at symbolIterator (/codebuild/output/src008293549/src/node_modules/neo-async/async.js:3485:9)
361 | at done (/codebuild/output/src008293549/src/node_modules/neo-async/async.js:3527:9)
362 | at Hook.eval [as callAsync] (eval at create (/codebuild/output/src008293549/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
363 | at /codebuild/output/src008293549/src/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:4984:43
364 | at symbolIterator (/codebuild/output/src008293549/src/node_modules/neo-async/async.js:3482:9)
365 | at timesSync (/codebuild/output/src008293549/src/node_modules/neo-async/async.js:2297:7)

`
I'm on Angular 13.3.5
I've downgraded my project version to 0.1.6 for now.

**Comment by miraxes** [comment]
Hello @noskap, just created https://stackblitz.com/edit/angular-scss-demo-sbpqs2?file=src/styles.scss , seems like everything works as expected (ugly styles doesn't count).
I'm not sure what can I fix in lib.
Can you recreate those bug on fresh app? And double check your webpack config maybe. :(

**Comment by noskap** [comment]
Just tested on a fresh angular project (v13) and it's working perfectly. It must've just been the monolith project I was on. Sorry about that. Will fix my local project
